name: Check Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check:
    name: Check one of the required semver labels is present
    runs-on: ubuntu-latest

    steps:
      - name: Check the labels
        uses: Pezmc/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'major, minor, patch, internal, documentation'
          disable-reviews: true
